import Foundation

/// The map style for the offline basemap.
///
/// `basemap-light.json` and `basemap-dark.json` (generated by `tools/style/generate.mjs`) refer to the tiles and
/// glyphs through two placeholders. They are replaced here with file URLs inside the app bundle, so the map needs
/// no network.
enum BaseStyle {
  static func url(dark: Bool) -> URL {
    let bundle = Bundle.main
    guard
      let templateURL = bundle.url(forResource: dark ? "basemap-dark" : "basemap-light", withExtension: "json"),
      var json = try? String(contentsOf: templateURL, encoding: .utf8),
      let tiles = bundle.url(forResource: "madison", withExtension: "pmtiles"),
      let resources = bundle.resourceURL
    else { return plainStyle(dark: dark) }
    json = json.replacingOccurrences(of: "__PMTILES__", with: tiles.absoluteString)
    json = json.replacingOccurrences(of: "__GLYPHS__", with: resources.appendingPathComponent("glyphs").absoluteString)
    return write(json, name: dark ? "headway-dark-style.json" : "headway-light-style.json")
  }

  /// A background-only style: what the map shows if the basemap files are missing from the bundle.
  private static func plainStyle(dark: Bool) -> URL {
    let json = """
      {
        "version": 8,
        "name": "Headway plain",
        "sources": {},
        "layers": [
          { "id": "background", "type": "background", "paint": { "background-color": "\(dark ? "#1C1C1E" : "#EEEBE4")" } }
        ]
      }
      """
    return write(json, name: dark ? "headway-plain-dark.json" : "headway-plain-light.json")
  }

  private static func write(_ json: String, name: String) -> URL {
    let file = FileManager.default.temporaryDirectory.appendingPathComponent(name)
    try? Data(json.utf8).write(to: file)
    return file
  }
}
