import Foundation

/// The map style for the offline basemap.
///
/// `basemap-style.json` (generated by `tools/style/generate.mjs`) refers to the tiles and glyphs through two
/// placeholders. They are replaced here with file URLs inside the app bundle, so the map needs no network.
enum BaseStyle {
  static let url: URL = {
    let bundle = Bundle.main
    guard
      let templateURL = bundle.url(forResource: "basemap-style", withExtension: "json"),
      var json = try? String(contentsOf: templateURL, encoding: .utf8),
      let tiles = bundle.url(forResource: "madison", withExtension: "pmtiles"),
      let resources = bundle.resourceURL
    else { return plainStyle() }
    json = json.replacingOccurrences(of: "__PMTILES__", with: tiles.absoluteString)
    json = json.replacingOccurrences(of: "__GLYPHS__", with: resources.appendingPathComponent("glyphs").absoluteString)
    return write(json, name: "headway-basemap-style.json")
  }()

  /// A background-only style: what the map shows if the basemap files are missing from the bundle.
  private static func plainStyle() -> URL {
    let json = """
      {
        "version": 8,
        "name": "Headway plain",
        "sources": {},
        "layers": [
          { "id": "background", "type": "background", "paint": { "background-color": "#EEEBE4" } }
        ]
      }
      """
    return write(json, name: "headway-plain-style.json")
  }

  private static func write(_ json: String, name: String) -> URL {
    let file = FileManager.default.temporaryDirectory.appendingPathComponent(name)
    try? Data(json.utf8).write(to: file)
    return file
  }
}
